### ISSUE TITLE
Question about setting up ShowDepth Quad in a new project

### ISSUE THREAD

**Issue by shrekshao** [sugi-cho/Unity-GPU-Particle#1]
Hi sugi-cho

Thanks for the great project. 

I'm learning to the ShowDepth RenderTarget part. I tried to setup the same thing in a new scene created under your project and another same scene in a newly created project (I'm using 2017.2)

The strange thing is that this ShowDepth Material is working in the scene created within your project, but not in my newly created project. 

![image](https://user-images.githubusercontent.com/5031596/34245337-570b39ca-e5de-11e7-8620-01eb126de7ff.png)

I think only these files are necessary for getting the depth render texture to work: 
![image](https://user-images.githubusercontent.com/5031596/34245370-7acfbd04-e5de-11e7-8b03-880aa31e854e.png)

Am I missing any components? Or is there a special project configuration? Or it might be caused by an upgraded of the project file (I think yours is originally in 5.x)

Thanks!

**Comment by shrekshao** [comment]
I fixed the issue by changing the `CameraEvent` Stage for `AddCommandBuffer`. It was BeforeGBuffer and is related to defer pipeline so it might not work for default project setting using forward pipeline.

Thanks again for sharing this project!

**Comment by sugi-cho** [comment]
oh, thank you!
(I was busy at work and I was late for the response..

thanks again
